### ISSUE TITLE
Unable to perform an scan using Github Actions - No module named 'MobSF'

### ISSUE THREAD

**Issue by bartosz-naumowicz** [inm-certi/mobsf-action#5]
Hello,
since around 1 month we are unable to perform a scan of our code. Looks like gunicorn is unable to start a thread throwing "No module named 'MobSF'" error. Below you can find output.

`[2021-02-12 09:16:08 +0000] [47] [INFO] Starting gunicorn 20.0.4
[2021-02-12 09:16:08 +0000] [47] [INFO] Listening at: http://127.0.0.1:8000 (47)
[2021-02-12 09:16:08 +0000] [47] [INFO] Using worker: threads
[2021-02-12 09:16:08 +0000] [50] [INFO] Booting worker with pid: 50
Error: 2-12 09:16:08 +0000] [50] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'MobSF'
[2021-02-12 09:16:08 +0000] [50] [INFO] Worker exiting (pid: 50)
[2021-02-12 09:16:08 +0000] [47] [INFO] Shutting down: Master
[2021-02-12 09:16:08 +0000] [47] [INFO] Reason: Worker failed to boot.
[/api/v1/upload] Upload the app to MobSF
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8000: Connection refused` 

Do you have any idea what might be causing this error?

**Comment by seletivo-certi-cdm** [comment]
Hello,

Which branch/tag are you using? 1.3? Can you try to use "master"? 
```
      - name: Run MobSF Analysis
        uses: inm-certi/mobsf-action@v1.3
        env:
        inm-certi/mobsf-action@v1.3
```

MobSF has recently made a directory change (https://github.com/inm-certi/mobsf-action/pull/4) and I couldn't update the README and create another tag.

**Comment by inm-certi** [comment]
Hello,

Which branch/tag are you using? 1.3? Can you try to use "master"?
```
      - name: Run MobSF Analysis
        uses: inm-certi/mobsf-action@master
```
MobSF has recently made a directory change (#4) and I couldn't update the README and create another tag.

**Comment by bartosz-naumowicz** [comment]
Will try with the master.

**Comment by marcelosarquis** [comment]
@inm-certi Thank you for your response. If the work on master is done, it would be great to rely on a released version instead of the master branch. Are you/the team working working on something else to include on master before creating a new tag?
Cheers.

**Comment by marcelosarquis** [comment]
@inm-certi @ajinabraham any feedback here, please?

**Comment by ajinabraham** [comment]
I am sorry, I have no idea. Please wait for a response from @inm-certi

**Comment by ianmaciel** [comment]
> @inm-certi Thank you for your response. If the work on master is done, it would be great to rely on a released version instead of the master branch. Are you/the team working working on something else to include on master before creating a new tag?
> Cheers.

I'm sorry, I had not seen this before.

I'm not working on anything else, so yes, I should release on master. I was just waiting @bartosz-naumowicz, to make sure it is working. (I can't test right now, I don't have more any project running this action).

**Comment by inm-certi** [comment]
@bartosz-naumowicz Did you have the chance to test it? Did it work?

**Comment by inm-certi** [comment]
Well.. in the meanwhile I updated the release on Github marketplace.
I will wait the feedbacks to close this issue.

**Comment by bartosz-naumowicz** [comment]
@inm-certi Yes, master version worked. Issue was not longer present.
